import type { Exercise, MuscleGroup } from "@/types";

export const DEFAULT_EXERCISES = [
  "Back Squat",
  "Barbell Row",
  "Bench Press",
  "Bent Over Row",
  "Bicep Curl",
  "Calf Raise",
  "Chest Fly",
  "Conventional Deadlift",
  "Dumbbell Bench Press",
  "Dumbbell Row",
  "Face Pull",
  "Front Squat",
  "Hammer Curl",
  "Incline Bench Press",
  "Lat Pulldown",
  "Lateral Raise",
  "Leg Curl",
  "Leg Extension",
  "Leg Press",
  "Lunges",
  "Overhead Press",
  "Plank",
  "Pull Up",
  "Push Up",
  "Romanian Deadlift",
  "Seated Dumbbell Shoulder Press",
  "Skull Crusher",
  "Tricep Pushdown",
] as const;

const MUSCLE_GROUP_BY_NAME: Record<(typeof DEFAULT_EXERCISES)[number], MuscleGroup> = {
  "Back Squat": "legs",
  "Barbell Row": "back",
  "Bench Press": "chest",
  "Bent Over Row": "back",
  "Bicep Curl": "arms",
  "Calf Raise": "legs",
  "Chest Fly": "chest",
  "Conventional Deadlift": "back",
  "Dumbbell Bench Press": "chest",
  "Dumbbell Row": "back",
  "Face Pull": "shoulders",
  "Front Squat": "legs",
  "Hammer Curl": "arms",
  "Incline Bench Press": "chest",
  "Lat Pulldown": "back",
  "Lateral Raise": "shoulders",
  "Leg Curl": "legs",
  "Leg Extension": "legs",
  "Leg Press": "legs",
  Lunges: "legs",
  "Overhead Press": "shoulders",
  Plank: "core",
  "Pull Up": "back",
  "Push Up": "chest",
  "Romanian Deadlift": "legs",
  "Seated Dumbbell Shoulder Press": "shoulders",
  "Skull Crusher": "arms",
  "Tricep Pushdown": "arms",
};

const slugify = (name: string) => name.toLowerCase().replace(/\s+/g, "-");

export const SEED_EXERCISES: Exercise[] = DEFAULT_EXERCISES.map((name) => ({
  id: slugify(name),
  name,
  muscleGroup: MUSCLE_GROUP_BY_NAME[name],
}));
